# Generated by Django 4.2.28 on 2026-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content', max_length=255)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('news', 'News'), ('education', 'Education')], db_index=True, help_text='Content Category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
